package com.rescuegrid.event;

public enum EventType {
    INCIDENT_CREATED, INCIDENT_ESCALATED, INCIDENT_RESOLVED,
    RESOURCE_ASSIGNED, RESOURCE_RELEASED, VEHICLE_DISPATCHED, VEHICLE_ARRIVED,
    HOSPITAL_FULL, HOSPITAL_AVAILABLE, ROAD_CLOSED, ROAD_OPENED,
    VEHICLE_FAILED, PATIENT_ADMITTED, PATIENT_DISCHARGED,
    SUPPLY_DEPLETED, TRAFFIC_CONGESTED, EMERGENCY_VEHICLE_PASSING,
    SIMULATION_STARTED, SIMULATION_PAUSED, SIMULATION_RESUMED, SIMULATION_STOPPED,
    MASS_CASUALTY, FAILURE_INJECTED, METRICS_UPDATED, BENCHMARK_COMPLETED
}
